name: Upload Dockerfile on docker hub
on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  buid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build dockerfile
        run: docker build . -t garage_flow_v1
        
