version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
      - "5001:8443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=GarageFlowServiceDb;User Id=sa;Password=FIAP@2026;TrustServerCertificate=True;
      - Jwt__Key=GarageFlowServiceSecretKey2024!SuperSecure
      - Jwt__Issuer=GarageFlowService
      - Jwt__Audience=GarageFlowServiceClients
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - workshop-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "FIAP@2026"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./seed-database.sql:/var/opt/mssql/seed-database.sql
      - ./init-database.sh:/var/opt/mssql/init-database.sh
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "FIAP@2026" -Q "SELECT 1" -No
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - workshop-network
    command: >
      /bin/bash -c "
      /opt/mssql/init-database.sh &
      /opt/mssql-tools18/bin/sqlservr
      "

volumes:
  sqlserver_data:

networks:
  workshop-network:
    driver: bridge
