version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
      - "5001:8443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=garage-flow.cxcyk20y6fws.us-east-2.rds.amazonaws.com,1433;Database=garage_flow;User Id=garage_flow;Password=root12345;Encrypt=True;TrustServerCertificate=True;
      - Jwt__Key=GarageFlowServiceSecretKey2024!SuperSecure
      - Jwt__Issuer=GarageFlowService
      - Jwt__Audience=GarageFlowServiceClients
    networks:
      - workshop-network

networks:
  workshop-network:
    driver: bridge
