apiVersion: v1
kind: ConfigMap
metadata:
  name: garageflow-config
data:
  ASPNETCORE_ENVIRONMENT: Production
  ASPNETCORE_URLS: http://+:8080
  Jwt__Issuer: GarageFlowService
  Jwt__Audience: GarageFlowServiceClients
  Auth__AdminUser: admin
  Logging__LogLevel__Default: Information