apiVersion: apps/v1
kind: Deployment
metadata:
  name: garage-flow-deployment
  namespace: garage-flow-namespace
  labels:
    app: garage-flow-deployment
    env: prod
spec:
  selector:
    matchLabels:
      app: garage-flow-app
  template:
    metadata:
      labels:
        app: garage-flow-app
    spec:
      containers:
        - name: garage-flow
          image: raphaelbrodrigues/garage_flow_v1
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
              name: garage-flow-configmap
