apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: garageflow
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - sqlserver-deployment.yaml
  - sqlserver-service.yaml
  - api-deployment.yaml
  - api-service.yaml
  - hpa.yaml