apiVersion: v1
kind: Secret
metadata:
  name: garageflow-secrets
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: Server=garageflow-sqlserver,1433;Database=GarageFlowServiceDb;User Id=sa;Password=ChangeMe!123;TrustServerCertificate=True;
  Jwt__Key: GarageFlowServiceSecretKey2024!SuperSecure
  Auth__AdminPassword: Admin@123
  MSSQL_SA_PASSWORD: ChangeMe!123