apiVersion: v1
kind: Secret
metadata:
  name: garageflow-secrets
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: Server=garage-flow.cxcyk20y6fws.us-east-2.rds.amazonaws.com,1433;Database=garage_flow;User Id=garage_flow;Password=root12345;Encrypt=True;TrustServerCertificate=True;
  Jwt__Key: GarageFlowServiceSecretKey2024!SuperSecure
  Auth__AdminPassword: Admin@123
