apiVersion: v1
kind: Service
metadata:
  name: garage-flow-service
  namespace: garage-flow-namespace
spec:
  selector:
    app: garage-flow-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
