apiVersion: apps/v1
kind: Deployment
metadata:
  name: garageflow-sqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: garageflow-sqlserver
  template:
    metadata:
      labels:
        app: garageflow-sqlserver
    spec:
      containers:
        - name: sqlserver
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_PID
              value: Express
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: garageflow-secrets
                  key: MSSQL_SA_PASSWORD
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1
              memory: 1Gi