name: deploy on EKS
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  run-kubectl:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.EKS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.EKS_SECRET_KEY }}
      AWS_DEFAULT_REGION: us-east-2
    steps:
      - uses: actions/checkout@v4
      - name: configure aws credentials
        run: aws sts get-caller-identity
      - name: update kubeconfig
        run: aws eks update-kubeconfig --region us-east-2 --name garage_flow_eks
      - name: deploy to eks
        run: kubectl apply -f k8s/
      - name: restart deployment
        run: kubectl rollout restart garage-flow-deployment -n garage-flow-namespace
